on: [push]

jobs:
  build:
    name: Build Nix flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/flake-checker-action@v4
        with:
          check-outdated: false
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: rpypkgs
          skipPush: true
      - name: Build Nix flake
        run: nix build
      - name: Fix permissions
        run: cp --recursive --dereference --no-preserve=mode,ownership result/share public
      - uses: actions/upload-pages-artifact@v4
        with:
          path: public/
  deploy:
    needs: build
    name: Deploy GH Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
